### ISSUE TITLE
Copy ability ID

### ISSUE THREAD

**Issue by AndersonLT** [mitre/chain#78]
By default Ability ID isn't selectable.

Current code:
`<td><input id="ability-id" disabled/></td>` 

Fixed code:

`<td><input id="ability-id"/></td>`

Don't know if this is a bug, but this really make things more difficulty

**Comment by privateducky** [comment]
it was intentional to not let a user modify the ID field (like you can all the other fields in the ability section). you can still select the field to copy/paste the ID, you just cannot edit the text on screen. 

what action are you trying to complete?

**Comment by privateducky** [comment]
we noticed this was a FireFox issue ^^ not reproducible on chrome. that said-- I pushed a fix just now.
