### ISSUE TITLE
Adversary window is blank

### ISSUE THREAD

**Issue by xenoscr** [mitre/chain#87]
When cycling through the three options for each adversary nothing is being displayed. JavaScript errors are occurring as well when attempting to cycle though the options. See the screenshot.

![image](https://user-images.githubusercontent.com/2199813/61974819-734edb80-afb5-11e9-8e51-f932f6612def.png)

**Comment by wbooth** [comment]
Hey, 

You may want to do a fresh clone. Looks like you may have a submodule out of sync.

you can either delete and start new or try the following:
git reset --hard origin/master && git checkout master && git reset --hard origin/master && git pull && git submodule foreach git checkout master && git submodule foreach git pull

**Comment by xenoscr** [comment]
That was a fresh clone I did yesterday. Everything was as it was in the repository.

**Comment by xenoscr** [comment]
ok, very strange, works now. It was a fresh pull in a brand new directory. I was attempting to make sure my new plugin plays well with the current version of caldera and it's plugins.
