### ISSUE TITLE
Unable to edit or create adversaries (May or may not be related to issue #87)

### ISSUE THREAD

**Issue by xenoscr** [mitre/chain#88]
This may or may not be related to issue #87 but, I am unable to create a new adversary or edit existing adversaries.

**Comment by wbooth** [comment]
Adversaries are no longer edited through the Gui. You can edit adversaries in stockpile/adversaries.yml file

**Comment by xenoscr** [comment]
Ok, seems like that is a bit of a step backward as far as usability.
